name: Scrape RBI Updates
on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours (0 minutes past the hour)
  workflow_dispatch:  # Allows manual triggering
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install feedparser pymongo python-dotenv
    - name: Run scraper
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: python scraper.py